export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";
export const AUTH_SET_USER_DATA = "AUTH_SET_USER_DATA";
export const AUTH_RESET_STATE = "AUTH_RESET_STATE";
export const SCRAPE_POSTS = "SCRAPE_POSTS";
export const AUTH_SET_POST_DATA = "AUTH_SET_POST_DATA";
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const RESET_COUNT = "RESET_COUNT";
export const LOAD_MORE_COUNTS = "LOAD_MORE_COUNTS";
export const LOAD_MORE_ALL = "LOAD_MORE_ALL";
export const LOAD_MORE_IMG = "LOAD_MORE_IMG";
export const LOAD_MORE_VID = "LOAD_MORE_VID";
export const UI_MINRANGE_LIKES = "UI_MINRANGE_LIKES";
export const UI_MAXRANGE_LIKES = "UI_MAXRANGE_LIKES";
export const UI_MINRANGE_VIEWS = "UI_MINRANGE_VIEWS";
export const UI_MAXRANGE_VIEWS = "UI_MAXRANGE_VIEWS";
export const RESET_RANGE = "RESET_RANGE";
export const UNFOUND_USER = "UNFOUND_USER";
export const GET_INFLUENCERS = "GET_INFLUENCERS";
export const RESET_INFLUENCERS = "RESET_INFLUENCERS";
export const RESET_UNFOUND_USER = "RESET_UNFOUND_USER";


